### ISSUE TITLE
0.9.1 から 0.10.0へのバージョンアップによる課題登録エラー

### ISSUE THREAD

**Issue by d-moritani** [nulab/backlog-js#11]
Backlog APIを使わせていただいているのですが、
backlog-jsのバージョンを 0.9.1 から 0.10.0 にアップデートすると、
Backlogへ下記文字列を含んだ課題を投稿すると、失敗するようになりました。
> ''&color(#ffffff, #ff0000) { 赤背景白文字 }''

回避策などがあれば教えていただけますでしょうか。
よろしくお願いします。

**Comment by mmktomato** [comment]
ご報告ありがとうございます。調査します。

**Comment by mmktomato** [comment]
@d-moritani 先程修正バージョンをリリースしました。0.11.0 をお試しください。
