### ISSUE TITLE
Add type annotation for response

### ISSUE THREAD

**Issue by odanado** [nulab/backlog-js#28]
There are no type annotations in [backlog.ts](
https://github.com/nulab/backlog-js/blob/fdb038998b5763d642487bf26034c7fba52f1aa8/src/backlog.ts#L16). This detracts from the developer experience.

I am interested in this task. Can I work on it?

**Comment by mmktomato** [comment]
Sure!
Do you mean about return types? Parameters have types already. https://github.com/nulab/backlog-js/blob/master/src/backlog.ts

**Comment by odanado** [comment]
> Do you mean about return types?

Yes.
But, most of the return types are of type any, which can be confusing for developers.

**Comment by mmktomato** [comment]
Good.
Let me know if you have any problems on the implementation.

**Comment by mmktomato** [comment]
I'm working on this issue. This will come with some breaking changes.

**Comment by mmktomato** [comment]
Done.
The details of breaking changes: https://github.com/nulab/backlog-js/pull/77#issue-1737466728
