### ISSUE TITLE
Add deprecated annotation for Deprecated API

### ISSUE THREAD

**Issue by odanado** [nulab/backlog-js#29]
TypeScript 4.0 and later versions show strikethrough when `@deprecated ` is written in a JSDoc comment.

ref: https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/#deprecated-support

This is useful to inform developers that some APIs, such as https://developer.nulab.com/docs/backlog/api/2/get-list-of-groups/#, are deprecated.

**Comment by mmktomato** [comment]
I added `@deprecated` annotations to some methods. This will ship in next release. Thank you for your report!
