### ISSUE TITLE
Error on postIssue with categoryId

### ISSUE THREAD

**Issue by Herdubreid** [nulab/backlog-js#4]
When posting the following issue:
```
{
  categoryId: 22853
  description: "Test 2"
  issueTypeId: 87099
  priorityId: 2
  projectId: 20805
  summary: "Test 2"
}
```
The following error is returned:
```
{
  message: "error.unknownParameter : categoryId",
  code: 7,
  moreInfo: ""
}
```
After removing the `categoryId` parameter, the issue is successfully posted.

**Comment by mmktomato** [comment]
Hi. Sorry for late reply.
The type of `categoryId` is `Array<number>`. https://github.com/nulab/backlog-js/blob/4483f3b436467cf51c5e28ce8a5fa0c00c3666ea/src/option.ts#L345
Try like this:
```
{
  categoryId: [22853]
}
```
