### ISSUE TITLE
Search for tickets that does not set start date 

### ISSUE THREAD

**Issue by siquylee** [nulab/backlog-js#73]
Hi,

I could not find any documents in API list to query all tickets that have startDate is unset. Could you provide some information?

Thanks

**Comment by mmktomato** [comment]
Backlog API doesn't have exact feature.

Instead, you can do sort by `startDate` `asc`.
https://developer.nulab.com/docs/backlog/api/2/get-issue-list/#query-parameters

If you send a request with `sort=startDate` and `order=asc`, the API returns issues without startDate in priority.
