### ISSUE TITLE
type declaration of Entity.Issue.Issue has issues

### ISSUE THREAD

**Issue by tockri** [nulab/backlog-js#79]
Hi, thank you for great library!
I found subtle issues on `Issue` declaration.
https://github.com/nulab/backlog-js/blob/master/src/entity.ts#L233

```typescript
  export interface Issue {
    id: number;
     :
    keyId: 1;    // <---- should be number
     :
    resolution: Resolution; // <----- should be Resolution | undefined
     :
    assignee: User.User; // <------ should be User.User | undefined
     :
  }
```
Please consider fixing 🙏

**Comment by mmktomato** [comment]
@tockri Thank you for the report! I fixed it and released 0.13.1.
